export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
export const GET_SEARCHED_BOOKS = 'GET_SEARCHED_BOOKS';
export const GET_BOOK_DETAILS = 'GET_BOOK_DETAILS';
export const SET_LOADING_INDICATOR = 'SET_LOADING_INDICATOR';
export const SET_ERROR_INDICATOR = 'SET_ERROR_INDICATOR';